name: Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Package
        run: make release
      - name: Upload workflow artifact
        uses: actions/upload-artifact@v1
        with:
          name: gopass.alfredworkflow
          path: gopass.alfredworkflow
